version: '3.3'

services:
  mujoco_ros_utils:
    image: mujoco_ros_utils:humble
    user: root
    container_name: mujoco_ros_utils
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile.windows
    volumes:
      - "../:/root/catkin_ws/src/mujoco_ros_utils/"
    privileged: True
    stdin_open: True
    command: bash